14 kurzusok menü elkészítése
me-kry-student-task-checker/stc-frontend pull request #20
Opened 2021-05-06 14:31 UTC by CsalaPeter

2021-06-09 18:52 UTC, kryzsu requested changes

2021-06-09 18:52 UTC, kryzsu commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  create(credentials: NewCourse): Observable<object> {
object helyet konkret tipus

2021-06-09 18:52 UTC, kryzsu commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  edit(credentials: Course): Observable<object> {
object helyet konkret tipus

2021-06-18 13:14 UTC, CsalaPeter commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  create(credentials: NewCourse): Observable<object> {
Javítva konkrét tipusra.

2021-06-18 13:14 UTC, CsalaPeter commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  edit(credentials: Course): Observable<object> {
Javítva konkrét tipusra.

2021-06-26 17:02 UTC, kryzsu requested changes

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  get(id: Course['id']): Observable<Course> {
sima tipus jobb lenne a Course[id] helyett.

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  edit(credentials: Course): Observable<Course> {
parameter nev biztos jo?

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/shared/error-dialog/error-dialog.component.html
> +        Something went wrong!
magyar

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/shared/error-dialog/error-dialog.component.html
> +        <b>Status Code: {{data.status}}</b>
magyar

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/shared/login/login.component.html
>                  <strong>Failed to sign in!</strong> Please check your credentials and try again.
magyarul

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/shared/login/login.component.html
> +                <a class='alert-link' (click)='requestResetPassword()'>Did you forget your password?</a>
magyarul

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/shared/login/login.component.html
>                  <span>You don't have an account yet?</span>
magyarul

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/app/shared/login/login.component.html
> +                <a class='alert-link' (click)='register()'>Register a new account</a>
magyarul

2021-06-26 17:02 UTC, kryzsu commented on src/main/webapp/index.html
> +    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
magyarul

2021-06-27 13:57 UTC, CsalaPeter commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  get(id: Course['id']): Observable<Course> {
Átirva simára.

2021-06-27 13:57 UTC, CsalaPeter commented on src/main/webapp/app/layouts/courses/courses.service.ts
> +  edit(credentials: Course): Observable<Course> {
Javítva

2021-06-27 13:58 UTC, CsalaPeter commented on src/main/webapp/app/shared/error-dialog/error-dialog.component.html
> +        Something went wrong!
Magyarítva

2021-06-27 13:58 UTC, CsalaPeter commented on src/main/webapp/app/shared/error-dialog/error-dialog.component.html
> +        <b>Status Code: {{data.status}}</b>
Magyarítva

2021-06-27 13:58 UTC, CsalaPeter commented on src/main/webapp/app/shared/login/login.component.html
>                  <strong>Failed to sign in!</strong> Please check your credentials and try again.
Magyarítva

2021-06-27 13:58 UTC, CsalaPeter commented on src/main/webapp/app/shared/login/login.component.html
>                  <span>You don't have an account yet?</span>
Magyarítva

2021-06-27 13:58 UTC, CsalaPeter commented on src/main/webapp/app/shared/login/login.component.html
> +                <a class='alert-link' (click)='requestResetPassword()'>Did you forget your password?</a>
Magyarítva

2021-06-27 13:59 UTC, CsalaPeter commented on src/main/webapp/app/shared/login/login.component.html
> +                <a class='alert-link' (click)='register()'>Register a new account</a>
Magyarítva

2021-06-27 13:59 UTC, CsalaPeter commented on src/main/webapp/index.html
> +    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
Magyarítva

2021-10-28 11:48 UTC, merged